### PR TITLE
Build fix.  [TBR] (Fix #9)

### LINKED ISSUE #9: Build is failing

### PR DESCRIPTION
**Pull request by pq**
FYI @sethladd @lrhn @hterkelsen

### CODE REVIEW

**Comment by pq** [comment]
@lrhn : landing in the interest of fixing the build.  Feel free to update as you see fit.

**Comment by lrhn** [comment]
This package requires sdk 1.11 already, right? Is there someone working on a pre-release version of 1.11 before bleeding edge?

**Comment by pq** [comment]
This is a build thing (e.g., travis was failing).  I have it setup to use the `dev` branch but I'm not sure how that relates to `bleeding-edge`.  @sethladd ?

**Comment by sethladd** [comment]
dev is dev. :)

If you want to test on bleeding-edge, you'll have to modify your travis.sh script to grab the bleeding_edge build and put it on your path.

**Comment by pq** [comment]
OK, I guess that makes sense. :)

Next question: do we want to do this?

**Comment by sethladd** [comment]
1.11 is on the dev channel now. I'm not clear what you are asking.

**Comment by pq** [comment]
Sorry.  Do we want to point this build to bleeding-edge.

**Comment by sethladd** [comment]
will ping you on hangouts :)

**Comment by sethladd** [comment]
From chat: "The code in this repo relies on a constructor that currently ONLY is in bleeding_edge".

So, we can ask @ricowind when we think the next dev channel build will come out?

**Comment by ricowind** [comment]
We will ship 1.11.0-dev.3.0 as soon as https://github.com/dart-lang/www.dartlang.org/issues/1372 is fixed
I plan on doing another full push to be released on ~wed next week but I probably move that up to Monday if this is blocking people

**Comment by pq** [comment]
Actually, I think the issue isn't so much what's on `dev` as the fact that observatory builds with `stable`.  We've done a bunch of rollbacks elsewhere to address (see dart-lang/tools#1501) and will roll-forward when `1.11` is out the door.  IOW: no need to rush `dev` on our account!

**Pull request merged**
