### PR TITLE
Don't use Uri.directory

### PR DESCRIPTION
**Pull request by harryterkelsen**
Addresses another 1.11 dependency, see dart-lang/tools#1501 
@pq @sethladd

### CODE REVIEW

**Comment by sethladd** [comment]
Curious, wouldn't we assume that you'd use this library with 1.11 (dev or stable) ?

**Comment by harryterkelsen** [comment]
No, because in order to bootstrap the 1.11 SDK, you first need to build the runtime with the 1.10 SDK. Observatory is in the Dart runtime and depends on dart2js, which in turn depends on package_config. The 1.11 dependencies break observatory

**Comment by pq** [comment]
LGTM

**Comment by sethladd** [comment]
Interesting. cc @johnmccutchan

**Comment by sethladd** [comment]
If there's a link to a buildbot log file, that has the error, we can take a look.

**Comment by harryterkelsen** [comment]
```
$ tools/build.py -mrelease create_sdk
make -j 12 BUILDTYPE=ReleaseIA32 create_sdk
  ACTION runtime_dart_runtime_gyp_build_observatory_host_pub_build_observatory out/ReleaseIA32/observatory/build/web/index.html
Loading source assets... 
Loading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/defauLoading initialize/build/loader_replacer, initialize, observe, code_transformers/src/delete_file, polymer_interop/src/build/replace_polymer_js, smoke/src/default_transformer, web_components/build/mirrors_remover and web_components transformers... (1.4s) 
Loading polymer transformers... (1.5s) 
Building observatory... (4.6s) 
[Warning from polymer (PolymerBootstrapTransformer) on observatory|web/index.html]:
We have detected a cycle in your import graph when running initializers on ActionLinkElement. This means the super class ObservatoryElement has a dependency on this library (possibly transitive).
[Info from Dart2JS]:
Compiling observatory|web/index.html.polymer.bootstrap.dart...
[Error from Dart2JS]:
web/index.html.polymer.bootstrap.dart:
The compiler crashed when compiling this element.
The compiler is broken.

When compiling the above element, the compiler crashed. It is not
possible to tell if this is caused by a problem in your program or
not. Regardless, the compiler should not crash.

The Dart team would greatly appreciate if you would take a moment to
report this problem at http://dartbug.com/new.

Please include the following information:

* the name and version of your operating system,

* the Dart SDK build number (build number could not be determined), and

* the entire message you see here (including the full stack trace
  below as well as the source location above).

Build error:
Transform Dart2JS on observatory|web/index.html.polymer.bootstrap.dart threw error: No constructor 'Uri.directory' declared in class 'Uri'.

NoSuchMethodError: method not found: 'Uri.directory'
Receiver: Type: class 'Uri'
Arguments: ["/usr/local/google/home/het/code/dart/sdk/runtime/observatory/packages/polymer"]
dart:core                                            NoSuchMethodError._throwNew
package:package_config/src/packages_impl.dart 76:24  FilePackagesDirectoryPackages._getBase
package:package_config/src/packages_impl.dart 38:31  _PackagesBase.resolve
package:compiler/src/apiimpl.dart 343:28             Compiler.translatePackageUri
package:compiler/src/apiimpl.dart 287:49             Compiler.translateUri
package:compiler/src/apiimpl.dart 234:35             readScript
package:compiler/src/library_loader.dart 550:24      _LibraryLoaderTask.createLibrary.<fn>
package:compiler/src/compiler.dart 908:15            Compiler.withCurrentElement
package:compiler/src/library_loader.dart 549:39      _LibraryLoaderTask.createLibrary
package:compiler/src/library_loader.dart 519:25      _LibraryLoaderTask.registerLibraryFromTag
package:compiler/src/library_loader.dart 427:40      _LibraryLoaderTask.processLibraryTags.<fn>.<fn>.<fn>
package:compiler/src/compiler.dart 908:15            Compiler.withCurrentElement
package:compiler/src/library_loader.dart 426:43      _LibraryLoaderTask.processLibraryTags.<fn>.<fn>
dart:isolate                                         _RawReceivePortImpl._handleMessage

Build failed.
make: *** [out/ReleaseIA32/observatory/build/web/index.html] Error 65
BUILD FAILED
```

**Pull request merged**
