### PR TITLE
Create a forward/backwards compatible 1.9.0 version

### PR DESCRIPTION
**Pull request by lrhn**
This version includes both the old API and the new API. 

Impressively, there was no conflicts (mainly because the old API did not use the `package_config.dart` library name).

Maintains the location of files in `lib/src/` because someone might be importing them directly.

This version will allow a package to migrate to the new behavior without breaking packages depending on the old behavior.

### CODE REVIEW

**Comment by lrhn** [comment]
This review is for showing only, the branch should *not be merged* into master. It should be kept as 1.9 (or some other name).

**Review by jonasfj — APPROVED** [review]

**Review by jakemac53 — APPROVED** [review]

**Comment by jakemac53** [comment]
That is certainly an easier way to do it :D

**Comment by jakemac53** [comment]
Ideally we would actually merge this into the master branch and make `1.9` be the new true master.

We would then delete package_config 2.x from pub (@kevmoo has confirmed no real users are downloading it from pub yet and it can safely be deleted).

Then we can publish 2.x at some later date once things all settle down - or shortly after 1.9 is published either way.

**Comment by jonasfj** [comment]
We can also publish 2.1.0 and state in the changelog that 2.0.0 is an accidental release that should never be trusted.

Anyone with a version range `'>= 1.9.0 <3.0.0'` is unlikely to get `'2.0.0'`. In fact they'll never get 2.0.0, so long as dependency constraints are the same in 2.0.0 and 2.1.0 -- so 2.0.0 will only affects those that do explicit version pinning.

Removing 2.0.0 requires escalation as it's outside pub.dev/policy.

**Comment by jakemac53** [comment]
> Removing 2.0.0 requires escalation as it's outside pub.dev/policy.

It isn't outside of the policy because the policy is intentionally vague. There are only some examples listed, and this request meets the important criteria of one of them `The pub.dev moderators will ensure that no widespread usage of the package has begun, and if so, may unpublish the package.`.

The value of removing it is well worth it imo.

**Comment by kevmoo** [comment]
We've seen ONE download total of v2.0.0 – I don't think it's a concern

**Comment by lrhn** [comment]
I've continued work on this in 1.9-allow-overlap.

**Comment by kevmoo** [comment]
> I've continued work on this in 1.9-allow-overlap.

Should this PR be closed then?

**Pull request closed without merging**
