### PR TITLE
Update .gitignore to new `dart_tool` pub cache

### PR DESCRIPTION
**Pull request by pq**
See: https://github.com/dart-lang/sdk/issues/32030

@kevmoo

### CODE REVIEW

**Comment by kevmoo** [comment]
You may not want to delete `.pub` yet – unless you're sure folks aren't going to develop against this package in any non-latest -dev release...

**Comment by pq** [comment]
I think we should be safe since the only folks working on this are working in the SDK and so are sure to be very bleeding edge.  You OK living dangerously? ;)

**Comment by kevmoo** [comment]
We should update the SDK constraint to exclude stable then...

Or just do an add and keep `.pub` – we can do a big cleanup of this once v2 ships

**Comment by pq** [comment]
KK. Added `.pub` back.  PTAL.

**Review by kevmoo — APPROVED** [review]

**Pull request merged**
