### PR TITLE
Allow packages inside other packages' package-URI-roots.

### PR DESCRIPTION
**Pull request by lrhn**
This should fix *some* of the issues in internal Google code, where package exist inside other packages.

That's just a one-line change and one test, actually, the rest is clean-up.

I'm not sure it's a *good* change. The examples I have seen so far seem to be accidental "packages" which do not contain Dart code, and a clean-up of the package detection code might fix it.

### CODE REVIEW

**Review by jakemac53 — APPROVED** [review]

**Comment by kevmoo** [comment]
@lrhn – just need to run `dartfmt`

@jacob314 – are you coll w/ the recent updates?

@lrhn – please land this with a squash-merge (so the history isn't quite so colorful 😄 )

**Comment by kevmoo** [comment]
Er @jakemac53

**Comment by lrhn** [comment]
The files are formatted. Not sure what the travis/dartfmt issue is.

Will definitely squash!

**Comment by kevmoo** [comment]
Are we ready to land this?

**Comment by lrhn** [comment]
It's landed.

**Pull request merged**
