### PR TITLE
dartfmt and strong mode clean

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by pq** [comment]
LGTM.

Maybe update the changelog and bump the version too?

**Comment by kevmoo** [comment]
@pq nothing changed that would actually help any users – better to wait until there is something useful 😄

**Comment by pq** [comment]
But don't we want to pull this version into the SDK?  (IOW: update DEPS?)

**Comment by pq** [comment]
I was thinking a version bump to correspond with a rev tag would be cleanest but maybe you're right and we don't care?  Your call!

**Pull request merged**
